# Generated by Django 2.2 on 2019-08-12 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='合同编码')),
                ('contract_amount', models.FloatField(verbose_name='合同金额')),
                ('contract_date', models.DateField(verbose_name='合同签订时间')),
                ('contract_expire', models.DateField(verbose_name='合同到期时间')),
                ('allowance', models.FloatField(verbose_name='交叉补贴')),
            ],
            options={
                'verbose_name': '合同信息',
                'verbose_name_plural': '合同信息',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sid', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='专线号')),
                ('status', models.PositiveIntegerField(blank=True, choices=[(0, '正常'), (1, '拆机'), (2, '单停'), (3, '双停'), (4, '停机保号'), (5, '其他')], default=0, verbose_name='状态')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='计费金额')),
                ('receive_org', models.CharField(max_length=128, verbose_name='揽收组织')),
                ('PRODUCT_NAME', models.CharField(max_length=128, verbose_name='产品名称')),
                ('main_set', models.CharField(max_length=256, verbose_name='主套餐')),
                ('add_set', models.CharField(max_length=256, verbose_name='加装包')),
                ('product_quality', models.CharField(max_length=64, verbose_name='产品性质')),
                ('custom', models.CharField(max_length=128, verbose_name='客户名称')),
                ('address', models.CharField(max_length=256, verbose_name='安装地址')),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Contract', verbose_name='合同编码')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='揽收人')),
            ],
            options={
                'verbose_name': '专线信息',
                'verbose_name_plural': '专线信息',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandwidth', models.IntegerField(verbose_name='套餐带宽')),
                ('true_bandwidth', models.IntegerField(verbose_name='实际带宽')),
                ('net_management', models.CharField(max_length=16, verbose_name='集团网管监控')),
                ('sid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business.Product', verbose_name='专线号')),
            ],
            options={
                'verbose_name': '资源信息',
                'verbose_name_plural': '资源信息',
            },
        ),
    ]
